# Generated by Django 3.1.7 on 2021-09-24 04:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ToDoApp_Management', '0005_auto_20210924_0425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todomodel',
            name='category',
            field=models.ForeignKey(blank=True, limit_choices_to={'user': models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ToDoApp_Management.categorymodel'),
        ),
    ]
