# Generated by Django 3.1.7 on 2021-09-24 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToDoApp_Management', '0014_auto_20210924_0757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todomodel',
            name='content',
            field=models.CharField(max_length=50),
        ),
    ]
