# Generated by Django 3.1.7 on 2021-09-25 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ToDoApp_Management', '0017_auto_20210924_1512'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todomodel',
            options={'ordering': ('pub_date',)},
        ),
    ]
