# Generated by Django 3.1.7 on 2021-09-25 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToDoApp_Management', '0019_ordermodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='order',
            field=models.CharField(choices=[('asc', '期限昇順'), ('desc', '期限降順'), ('ctg_asc', 'カテゴリー昇順'), ('ctg_desc', 'カテゴリー降順')], default='期限昇順', max_length=10),
        ),
    ]
