# Generated by Django 3.1.7 on 2021-09-26 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToDoApp_Management', '0023_auto_20210925_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todomodel',
            name='pub_date',
            field=models.DateField(blank=True),
        ),
    ]
