# Generated by Django 3.1.7 on 2021-09-26 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToDoApp_Management', '0026_auto_20210926_0823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todomodel',
            name='priority',
            field=models.CharField(choices=[('important', '重要'), ('normal', '普通')], default='普通', max_length=20),
        ),
    ]
